name: Publish & Deploy
on:
    push:
    pull_request:
        branches:
            - master
jobs:
    publish-core:
        name: Publish trrack-core
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-versions: [12.x]
            fail-fast: false
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
     
            - name: Fetch all
              run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
            
            - name: Install Packages
              run: yarn install
     
            - name: Build Libraries
              run: yarn build

            - name: Create npmrc for publishing
              run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Try publish
              run: yarn release